### ISSUE TITLE
Slim down the fat jar for stroom-stat-shbase-filter

### ISSUE THREAD

**Issue by jc064522** [gchq/stroom-stats#1]
It currently contains unneeded dependencies, including hbase, hadoop, junit, and logback. These need excluding. Possibly a whitelist?

#### Links
http://unethicalblogger.com/2015/07/15/gradle-goodness-excluding-depends-from-shadow.html

https://github.com/johnrengelman/shadow/issues/220

**Comment by at055612** [comment]
Done, jar size now down to 1.5Mb
